# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CASTOR(object):
    def setupUi(self, CASTOR):
        CASTOR.setObjectName(_fromUtf8("CASTOR"))
        CASTOR.resize(777, 867)
        self.centralWidget = QtGui.QWidget(CASTOR)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.texteCheminTrafic = QtGui.QLineEdit(self.centralWidget)
        self.texteCheminTrafic.setObjectName(_fromUtf8("texteCheminTrafic"))
        self.gridLayout.addWidget(self.texteCheminTrafic, 4, 1, 1, 4)
        self.textePoidsmin = QtGui.QLabel(self.centralWidget)
        self.textePoidsmin.setObjectName(_fromUtf8("textePoidsmin"))
        self.gridLayout.addWidget(self.textePoidsmin, 11, 0, 1, 1)
        self.textePoidsmax = QtGui.QLabel(self.centralWidget)
        self.textePoidsmax.setObjectName(_fromUtf8("textePoidsmax"))
        self.gridLayout.addWidget(self.textePoidsmax, 11, 3, 1, 1)
        self.buttonTrafic = QtGui.QPushButton(self.centralWidget)
        self.buttonTrafic.setObjectName(_fromUtf8("buttonTrafic"))
        self.gridLayout.addWidget(self.buttonTrafic, 4, 0, 1, 1)
        self.texteCheminLigneInfluence = QtGui.QLineEdit(self.centralWidget)
        self.texteCheminLigneInfluence.setObjectName(_fromUtf8("texteCheminLigneInfluence"))
        self.gridLayout.addWidget(self.texteCheminLigneInfluence, 3, 1, 1, 4)
        self.textePoidsEssieumax = QtGui.QLabel(self.centralWidget)
        self.textePoidsEssieumax.setObjectName(_fromUtf8("textePoidsEssieumax"))
        self.gridLayout.addWidget(self.textePoidsEssieumax, 12, 3, 1, 1)
        self.longEssieuMin = QtGui.QDoubleSpinBox(self.centralWidget)
        self.longEssieuMin.setMaximum(1000.0)
        self.longEssieuMin.setProperty("value", 70.0)
        self.longEssieuMin.setObjectName(_fromUtf8("longEssieuMin"))
        self.gridLayout.addWidget(self.longEssieuMin, 15, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.buttonLigneInlfuence = QtGui.QPushButton(self.centralWidget)
        self.buttonLigneInlfuence.setObjectName(_fromUtf8("buttonLigneInlfuence"))
        self.gridLayout.addWidget(self.buttonLigneInlfuence, 3, 0, 1, 1)
        self.vitMin = QtGui.QSpinBox(self.centralWidget)
        self.vitMin.setMaximum(130)
        self.vitMin.setProperty("value", 50)
        self.vitMin.setObjectName(_fromUtf8("vitMin"))
        self.gridLayout.addWidget(self.vitMin, 13, 1, 1, 1)
        self.texteVitMin = QtGui.QLabel(self.centralWidget)
        self.texteVitMin.setObjectName(_fromUtf8("texteVitMin"))
        self.gridLayout.addWidget(self.texteVitMin, 13, 0, 1, 1)
        self.texteVitMax = QtGui.QLabel(self.centralWidget)
        self.texteVitMax.setObjectName(_fromUtf8("texteVitMax"))
        self.gridLayout.addWidget(self.texteVitMax, 13, 3, 1, 1)
        self.texteVitMoy = QtGui.QLabel(self.centralWidget)
        self.texteVitMoy.setObjectName(_fromUtf8("texteVitMoy"))
        self.gridLayout.addWidget(self.texteVitMoy, 10, 0, 1, 1)
        self.poidsMin = QtGui.QDoubleSpinBox(self.centralWidget)
        self.poidsMin.setMaximum(1000.0)
        self.poidsMin.setProperty("value", 200.0)
        self.poidsMin.setObjectName(_fromUtf8("poidsMin"))
        self.gridLayout.addWidget(self.poidsMin, 11, 1, 1, 1)
        self.poidsMax = QtGui.QDoubleSpinBox(self.centralWidget)
        self.poidsMax.setMaximum(1000.0)
        self.poidsMax.setProperty("value", 400.0)
        self.poidsMax.setObjectName(_fromUtf8("poidsMax"))
        self.gridLayout.addWidget(self.poidsMax, 11, 4, 1, 1)
        self.vitMoy = QtGui.QSpinBox(self.centralWidget)
        self.vitMoy.setMaximum(200)
        self.vitMoy.setProperty("value", 90)
        self.vitMoy.setObjectName(_fromUtf8("vitMoy"))
        self.gridLayout.addWidget(self.vitMoy, 10, 1, 1, 1)
        self.textePas = QtGui.QLabel(self.centralWidget)
        self.textePas.setObjectName(_fromUtf8("textePas"))
        self.gridLayout.addWidget(self.textePas, 10, 3, 1, 1)
        self.titreParam = QtGui.QLabel(self.centralWidget)
        self.titreParam.setObjectName(_fromUtf8("titreParam"))
        self.gridLayout.addWidget(self.titreParam, 9, 0, 1, 1)
        self.poidsEssieumin = QtGui.QDoubleSpinBox(self.centralWidget)
        self.poidsEssieumin.setMaximum(200.0)
        self.poidsEssieumin.setProperty("value", 60.0)
        self.poidsEssieumin.setObjectName(_fromUtf8("poidsEssieumin"))
        self.gridLayout.addWidget(self.poidsEssieumin, 12, 1, 1, 1)
        self.longCamionMax = QtGui.QDoubleSpinBox(self.centralWidget)
        self.longCamionMax.setMaximum(1000.0)
        self.longCamionMax.setProperty("value", 700.0)
        self.longCamionMax.setObjectName(_fromUtf8("longCamionMax"))
        self.gridLayout.addWidget(self.longCamionMax, 14, 4, 1, 1)
        self.texteLongmax = QtGui.QLabel(self.centralWidget)
        self.texteLongmax.setObjectName(_fromUtf8("texteLongmax"))
        self.gridLayout.addWidget(self.texteLongmax, 14, 3, 1, 1)
        self.vitesseMax = QtGui.QSpinBox(self.centralWidget)
        self.vitesseMax.setMaximum(200)
        self.vitesseMax.setProperty("value", 130)
        self.vitesseMax.setObjectName(_fromUtf8("vitesseMax"))
        self.gridLayout.addWidget(self.vitesseMax, 13, 4, 1, 1)
        self.longCamionMin = QtGui.QDoubleSpinBox(self.centralWidget)
        self.longCamionMin.setMaximum(1000.0)
        self.longCamionMin.setProperty("value", 70.0)
        self.longCamionMin.setObjectName(_fromUtf8("longCamionMin"))
        self.gridLayout.addWidget(self.longCamionMin, 14, 1, 1, 1)
        self.textePoidsEssieumin = QtGui.QLabel(self.centralWidget)
        self.textePoidsEssieumin.setObjectName(_fromUtf8("textePoidsEssieumin"))
        self.gridLayout.addWidget(self.textePoidsEssieumin, 12, 0, 1, 1)
        self.texteLongmin = QtGui.QLabel(self.centralWidget)
        self.texteLongmin.setObjectName(_fromUtf8("texteLongmin"))
        self.gridLayout.addWidget(self.texteLongmin, 14, 0, 1, 1)
        self.longEssieuMax = QtGui.QDoubleSpinBox(self.centralWidget)
        self.longEssieuMax.setMaximum(1000.0)
        self.longEssieuMax.setProperty("value", 700.0)
        self.longEssieuMax.setObjectName(_fromUtf8("longEssieuMax"))
        self.gridLayout.addWidget(self.longEssieuMax, 15, 4, 1, 1)
        self.pas = QtGui.QDoubleSpinBox(self.centralWidget)
        self.pas.setProperty("value", 1.0)
        self.pas.setObjectName(_fromUtf8("pas"))
        self.gridLayout.addWidget(self.pas, 10, 4, 1, 1)
        self.texteLongEssieumin = QtGui.QLabel(self.centralWidget)
        self.texteLongEssieumin.setObjectName(_fromUtf8("texteLongEssieumin"))
        self.gridLayout.addWidget(self.texteLongEssieumin, 15, 0, 1, 1)
        self.texteLongEssieumax = QtGui.QLabel(self.centralWidget)
        self.texteLongEssieumax.setObjectName(_fromUtf8("texteLongEssieumax"))
        self.gridLayout.addWidget(self.texteLongEssieumax, 15, 3, 1, 1)
        self.texteNbEssieuMin = QtGui.QLabel(self.centralWidget)
        self.texteNbEssieuMin.setObjectName(_fromUtf8("texteNbEssieuMin"))
        self.gridLayout.addWidget(self.texteNbEssieuMin, 16, 0, 1, 1)
        self.texteNbEssieuMax = QtGui.QLabel(self.centralWidget)
        self.texteNbEssieuMax.setObjectName(_fromUtf8("texteNbEssieuMax"))
        self.gridLayout.addWidget(self.texteNbEssieuMax, 16, 3, 1, 1)
        self.nbEssieuMin = QtGui.QSpinBox(self.centralWidget)
        self.nbEssieuMin.setProperty("value", 2)
        self.nbEssieuMin.setObjectName(_fromUtf8("nbEssieuMin"))
        self.gridLayout.addWidget(self.nbEssieuMin, 16, 1, 1, 1)
        self.buttonHistorique = QtGui.QPushButton(self.centralWidget)
        self.buttonHistorique.setObjectName(_fromUtf8("buttonHistorique"))
        self.gridLayout.addWidget(self.buttonHistorique, 33, 2, 1, 1)
        self.titreHisto = QtGui.QLabel(self.centralWidget)
        self.titreHisto.setObjectName(_fromUtf8("titreHisto"))
        self.gridLayout.addWidget(self.titreHisto, 20, 0, 1, 1)
        self.poidsEssieumax = QtGui.QDoubleSpinBox(self.centralWidget)
        self.poidsEssieumax.setMaximum(9000.0)
        self.poidsEssieumax.setProperty("value", 140.0)
        self.poidsEssieumax.setObjectName(_fromUtf8("poidsEssieumax"))
        self.gridLayout.addWidget(self.poidsEssieumax, 12, 4, 1, 1)
        self.buttonDefaut = QtGui.QPushButton(self.centralWidget)
        self.buttonDefaut.setObjectName(_fromUtf8("buttonDefaut"))
        self.gridLayout.addWidget(self.buttonDefaut, 33, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 17, 0, 1, 1)
        self.nbEssieuMax = QtGui.QSpinBox(self.centralWidget)
        self.nbEssieuMax.setProperty("value", 8)
        self.nbEssieuMax.setObjectName(_fromUtf8("nbEssieuMax"))
        self.gridLayout.addWidget(self.nbEssieuMax, 16, 4, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 34, 0, 1, 5)
        self.line_3 = QtGui.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 8, 0, 1, 1)
        self.buttonValider = QtGui.QPushButton(self.centralWidget)
        self.buttonValider.setObjectName(_fromUtf8("buttonValider"))
        self.gridLayout.addWidget(self.buttonValider, 33, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 19, 0, 1, 1)
        self.buttonEffet = QtGui.QPushButton(self.centralWidget)
        self.buttonEffet.setObjectName(_fromUtf8("buttonEffet"))
        self.gridLayout.addWidget(self.buttonEffet, 35, 0, 1, 1)
        self.texteEffet = QtGui.QLineEdit(self.centralWidget)
        self.texteEffet.setObjectName(_fromUtf8("texteEffet"))
        self.gridLayout.addWidget(self.texteEffet, 35, 1, 1, 4)
        self.buttonInfoFormat = QtGui.QPushButton(self.centralWidget)
        self.buttonInfoFormat.setObjectName(_fromUtf8("buttonInfoFormat"))
        self.gridLayout.addWidget(self.buttonInfoFormat, 0, 0, 1, 1)
        self.checkPoids = QtGui.QCheckBox(self.centralWidget)
        self.checkPoids.setObjectName(_fromUtf8("checkPoids"))
        self.gridLayout.addWidget(self.checkPoids, 25, 0, 1, 1)
        self.checkLongueur = QtGui.QCheckBox(self.centralWidget)
        self.checkLongueur.setObjectName(_fromUtf8("checkLongueur"))
        self.gridLayout.addWidget(self.checkLongueur, 24, 0, 1, 1)
        self.checkNombreEssieu = QtGui.QCheckBox(self.centralWidget)
        self.checkNombreEssieu.setObjectName(_fromUtf8("checkNombreEssieu"))
        self.gridLayout.addWidget(self.checkNombreEssieu, 30, 0, 1, 1)
        self.checkPoidsEssieu = QtGui.QCheckBox(self.centralWidget)
        self.checkPoidsEssieu.setObjectName(_fromUtf8("checkPoidsEssieu"))
        self.gridLayout.addWidget(self.checkPoidsEssieu, 28, 0, 1, 1)
        self.checkEffet = QtGui.QCheckBox(self.centralWidget)
        self.checkEffet.setObjectName(_fromUtf8("checkEffet"))
        self.gridLayout.addWidget(self.checkEffet, 31, 0, 1, 1)
        self.checkVitesse = QtGui.QCheckBox(self.centralWidget)
        self.checkVitesse.setObjectName(_fromUtf8("checkVitesse"))
        self.gridLayout.addWidget(self.checkVitesse, 22, 0, 1, 1)
        self.buttonSortie = QtGui.QPushButton(self.centralWidget)
        self.buttonSortie.setObjectName(_fromUtf8("buttonSortie"))
        self.gridLayout.addWidget(self.buttonSortie, 31, 1, 1, 1)
        self.checkTOUT = QtGui.QCheckBox(self.centralWidget)
        self.checkTOUT.setObjectName(_fromUtf8("checkTOUT"))
        self.gridLayout.addWidget(self.checkTOUT, 32, 0, 1, 1)
        self.texteSortie = QtGui.QLineEdit(self.centralWidget)
        self.texteSortie.setInputMask(_fromUtf8(""))
        self.texteSortie.setObjectName(_fromUtf8("texteSortie"))
        self.gridLayout.addWidget(self.texteSortie, 31, 2, 1, 3)
        self.checkDistanceEssieux = QtGui.QCheckBox(self.centralWidget)
        self.checkDistanceEssieux.setObjectName(_fromUtf8("checkDistanceEssieux"))
        self.gridLayout.addWidget(self.checkDistanceEssieux, 29, 0, 1, 1)
        self.checkTemps = QtGui.QCheckBox(self.centralWidget)
        self.checkTemps.setObjectName(_fromUtf8("checkTemps"))
        self.gridLayout.addWidget(self.checkTemps, 21, 0, 1, 2)
        CASTOR.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(CASTOR)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 777, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuCASTOR = QtGui.QMenu(self.menuBar)
        self.menuCASTOR.setObjectName(_fromUtf8("menuCASTOR"))
        CASTOR.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(CASTOR)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        CASTOR.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(CASTOR)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        CASTOR.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuCASTOR.menuAction())

        self.retranslateUi(CASTOR)
        QtCore.QMetaObject.connectSlotsByName(CASTOR)

    def retranslateUi(self, CASTOR):
        CASTOR.setWindowTitle(_translate("CASTOR", "CASTOR", None))
        self.textePoidsmin.setText(_translate("CASTOR", "Poids minimum", None))
        self.textePoidsmax.setText(_translate("CASTOR", "Poids maximum", None))
        self.buttonTrafic.setText(_translate("CASTOR", "Trafic", None))
        self.textePoidsEssieumax.setText(_translate("CASTOR", "Poids maximum/essieu", None))
        self.buttonLigneInlfuence.setText(_translate("CASTOR", "Ligne d\'influence", None))
        self.texteVitMin.setText(_translate("CASTOR", "Vitesse minimum", None))
        self.texteVitMax.setText(_translate("CASTOR", "Vitesse maximale", None))
        self.texteVitMoy.setText(_translate("CASTOR", "Vitesse moyenne", None))
        self.textePas.setText(_translate("CASTOR", "Pas de temps (ms)", None))
        self.titreParam.setText(_translate("CASTOR", "PARAMETRES DE FILTRES", None))
        self.texteLongmax.setText(_translate("CASTOR", "Longueur camion maximale", None))
        self.textePoidsEssieumin.setText(_translate("CASTOR", "Poids minimum/essieu", None))
        self.texteLongmin.setText(_translate("CASTOR", "Longueur camion minimum", None))
        self.texteLongEssieumin.setText(_translate("CASTOR", "Longueur essieu minimum", None))
        self.texteLongEssieumax.setText(_translate("CASTOR", "Longueur essieu maximale", None))
        self.texteNbEssieuMin.setText(_translate("CASTOR", "Nombre essieux minimum", None))
        self.texteNbEssieuMax.setText(_translate("CASTOR", "Nombre essieux maximum", None))
        self.buttonHistorique.setText(_translate("CASTOR", "Historique", None))
        self.titreHisto.setText(_translate("CASTOR", "HISTOGRAMMES EN SORTIE", None))
        self.buttonDefaut.setText(_translate("CASTOR", "Parametres par defaut", None))
        self.buttonValider.setText(_translate("CASTOR", "Valider", None))
        self.buttonEffet.setText(_translate("CASTOR", "Ouvir un fichier Effet", None))
        self.buttonInfoFormat.setText(_translate("CASTOR", "Aide", None))
        self.checkPoids.setText(_translate("CASTOR", "Poids", None))
        self.checkLongueur.setText(_translate("CASTOR", "Longueurs", None))
        self.checkNombreEssieu.setText(_translate("CASTOR", "Repartition du nombre d\'essieux", None))
        self.checkPoidsEssieu.setText(_translate("CASTOR", "Poids/Essieux", None))
        self.checkEffet.setText(_translate("CASTOR", "Effets", None))
        self.checkVitesse.setText(_translate("CASTOR", "Vitesses", None))
        self.buttonSortie.setText(_translate("CASTOR", "Fichier en sortie", None))
        self.checkTOUT.setText(_translate("CASTOR", "TOUT COCHER", None))
        self.checkDistanceEssieux.setText(_translate("CASTOR", "Distance entre 2 essieux consecutifs", None))
        self.checkTemps.setText(_translate("CASTOR", "Durees entre l\'arrivee de 2 camions consecutifs", None))
        self.menuCASTOR.setTitle(_translate("CASTOR", "CASTOR", None))

